TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += quantumnorthwest.db
DATA += quantumnorthwest.proto

#=======================================
include $(TOP)/configure/RULES
